### PR TITLE
Added Unity package manager support and added installation instructions to readme

### PR DESCRIPTION
**Pull request by LukasKastern**
With 2020.1 Unity finally added support to specify relative paths inside git repositories to specify the package.json location. This allows us to just drop a package.json into the /Facepunch.Steamworks directory, generate the metafiles and download the package through the package manager by using the git URL with the path appended to it.

If you want to try it out follow [these](https://docs.unity3d.com/Manual/upm-ui-giturl.html) instructions and use [this](https://github.com/LukasKastern/Facepunch.Steamworks.git?path=/Facepunch.Steamworks) url

### CODE REVIEW

**Comment by skibitsky** [comment]
That's a great PR 👍 
If it is accepted, then it will be possible to add Facepunch.Steamworks to [OpenUPM](https://openupm.com) for better version control

**Comment by kamyker** [comment]
You're missing non-windows dlls. Meta files add noise to non-Unity projects (and will break if anything other use .meta files).

Complete solution is in https://github.com/kamyker/Facepunch.Steamworks.Package. That way it can also be used as git submodule and contain Unity dependent code.

**Comment by LukasKastern** [comment]
Oh cool, I didn't know a branch already exists. Why didn't you make a pull request yet?

> You're missing non-windows dlls. 
Oh, Thanks I didn't notice that since the steam_api.dll and steam_api64.dll were already added to that directory.

> Meta files add noise to non-Unity projects (and will break if anything other use .meta files)
To me, it looks like your branch has quite a lot more .meta files than mine, or what are you referring to?

**Comment by kamyker** [comment]
> Oh cool, I didn't know a branch already exists. Why didn't you make a pull request yet?
As I said this repo is supposed to work in pure C# projects without Unity.
> To me, it looks like your branch has quite a lot more .meta files than mine, or what are you referring to?
My fork is modified to work only in Unity projects + merging changes from this repo is trivial.

**Comment by LukasKastern** [comment]
I'll close this for now. I personally wouldn't mind having some .meta files laying around but the idea of having a separate repository that also has Unity specific stuff in it sounds great to me.

**Pull request closed without merging**
