### PR TITLE
Fix Encoding

### PR DESCRIPTION
**Pull request by HMBSbige**
Some strings will not display correctly in default encoding.
Set to UTF-8 for fix it

### CODE REVIEW

**Comment by HMBSbige** [comment]
All `const char *` can change to `byte[]` ,then use `Encoding` to encode string.

And UTF-8 was designed for backward compatibility with ASCII.

I think they all can use `Encoding.UTF8`.

**Comment by HMBSbige** [comment]
Something wrong with this pr

>  Rich presence keys used in substitutions may only contain alphanumeric characters, underscores, and colons.

It's so complex for steam API string.

Some of them use ASCII, some use UTF-8, some use UTF-16, some even did not declare...

I will open a issue to make a list for these string.

**Comment by HMBSbige** [comment]
UTF-8 was designed for backward compatibility with ASCII and lots of parameters in steam api use UTF-8.

So I think it's necessary and feasible to use UTF-8 instead of ASCII.

This is a temporary solution and there may be a better solution.

**Comment by klaritan** [comment]
This needs to be merged ASAP. Some Workshops items won't upload if it contains Chinese & Japanese letters.

**Comment by garrynewman** [comment]
This should be fixed in v2

**Pull request closed without merging**
