### PR TITLE
Add GetGlobalIntDays/GetGlobalFloatDays/RequestGlobalStats as non-async

### LINKED ISSUE #344: RequestGlobalStats is not exposed
RequestGlobalStats only executes in GetGlobalIntDaysAsync and GetGlobalFloatDaysAsync.  

Expose it to request global stats manually.

### PR DESCRIPTION
**Pull request by trdwll**
Fixes #344

### CODE REVIEW

**Comment by garrynewman** [comment]
This is the wrong way to do this - we shouldn't be manually changing the generated files.

**Comment by trdwll** [comment]
@garrynewman Let me know if the newest commit is better when you have the time.

**Comment by garrynewman** [comment]
What's the point of this?

**Comment by trdwll** [comment]
No clue. Someone requested it so I added it. Feel free to close.

**Pull request closed without merging**
