### PR TITLE
AttachUgc leaderboard

### LINKED ISSUE #416: Unsure how to get a valid File type for AttachUgc.
Hi there,

Thanks for the great library.  I have been stumped on how to use `AttachUgc` with a leaderboard for a day or so now and I am unable to work out from the documentation/issues history available.

I am creating a new UGC file using:

```
var res = await Editor.NewCommunityFile
    .WithTitle("some title")
    .WithMetaData("metadata string")
    .SubmitAsync();
```
My metadata will most likely be some JSON string. I am able to retrieve this UGC based on the `FileId` result:

```
var item = await SteamUGC.QueryFileAsync(res.FileId);
```

I cannot see anything on `item` that would allow me to get a `Steamworks.Data.Ugc` type.

There was a similar issue closed without any resolution - https://github.com/Facepunch/Facepunch.Steamworks/issues/360

Is there any examples of `AttachUgc` or have I missed something simple/fundemental?

Thanks

### LINKED ISSUE #479: Steamworks.Data.Leaderboard.AttachUgc cannot be used
**Is your feature request related to a problem? Please describe.**
I have looked through the latest code in master, and it appears there is no way to be able to use `Steamworks.Data.Leaderboard.AttachUgc()`. It takes, as a parameter `Steamworks.Data.Ugc`, but upon looking up references in the code base, there seems to be no way to query, or create one.

**Describe alternatives you've considered**
My goal is to be able to attach replay data to a workshop item for each user. So, players can pull down a workshop item and then a relevant replay from the leaderboard.

I had planned on using `Steamworks.Ugc.Editor.NewCommunityFile()` to generate a json file with a hidden tag, and then using `Steamworks.Ugc.Query.Items.WithFileId()` to get the exact file necessary. Then I had planned to somehow attach the `Steamworks.Ugc.Item` to the leaderboard, but I don't see a way of it being possible.

**Describe the solution you'd like**
Two possible solutions:
- a way to attach ugh to a leaderboard item
- another viable solution to generating and downloading replay data from steam 

**Additional context**
I was looking in the latest code in `master`, so there could be a solution I am not aware of.

### PR DESCRIPTION
**Pull request by kamyker**
Fixes #479
Fixes #416 

I've tried using older apis to make single UgcHandle with FileShare, UGCDownload and UGCDownloadToLocation but these things are bugged or no docs somehow make me use them incorrectly.

Anyway newer ugc work fine.

### CODE REVIEW

**Comment by ambid17** [comment]
@kamyker Do you have an open source repo I can look at to see how you made this work?

**Comment by kamyker** [comment]
@ambid17 first repo in my profile

**Comment by ambid17** [comment]
@kamyker Sorry for the ambiguity. I looked at your PR and I understand how this works in FacePunch. I can't seem to figure out how to use it in practice. Whenever you update a leaderboard score, it clears the attachedUgcId. How do you keep track of the file once it's been unlinked so you can update it?

**Comment by kamyker** [comment]
@ambid17 not sure what you mean, if u updated a score then old one is invalid and u have to attach new one

**Comment by ambid17** [comment]
ah, that's why it didn't work, thanks!

**Comment by kamyker** [comment]
@ambid17 oh and also before updating a score u should delete attached ugc from workshop, dno if there's a better way

instead I've also tried to delete ugc right after attaching it - worked correctly it was deleted from workshop and could still read from attachment, the only problem was that sometimes deletion failed

**Comment by ambid17** [comment]
I learned that you can just use this to make them hidden and then it's not a big deal: https://github.com/Facepunch/Facepunch.Steamworks/pull/509

**Comment by kamyker** [comment]
@ambid17 interesting, this items can still be downloaded by other players?

**Comment by ambid17** [comment]
@kamyker yep!

**Pull request closed without merging**
