### PR TITLE
more ugc download validation

### PR DESCRIPTION
**Pull request by kamyker**
[DownloadItem](https://partner.steamgames.com/doc/api/ISteamUGC#DownloadItem)
> The DownloadItemResult_t callback contains the app ID associated with the workshop item. It should be compared against the running app ID as the handler will be called for all item downloads regardless of the running application.

maybe this time i didn't miss anything from docs :D

`struct DownloadItemResult_t` could stay internal but then 
```
static event Action<DownloadItemResult_t> OnDownloadItemResult
```
has to also be internal and Download() summary would have to be changed:
```
/// <summary>
/// Start downloading this item. You'll get notified of completion via OnDownloadItemResult.
/// </summary>
```

### CODE REVIEW

**Comment by garrynewman** [comment]
You've made DownloadItemResult_t public :-(

**Comment by kamyker** [comment]
> You've made DownloadItemResult_t public :-(
oh wait I've forgot that's generated

**Comment by kamyker** [comment]
Ignore this for now, item.IsInstalled is true what breaks forced item updated.

I'm getting weird results with every implementation I can think of, sometimes players simply don't receive DownloadItemResult_t callback.

**Comment by kamyker** [comment]
Trying this in production, will update in few days if all good.

Had to add: `bool highPriority = true` as when using high priority, when trying to download multiple items, steam can get stuck and requires game restart to finish downloads.

**Comment by kamyker** [comment]
Haven't heard any complaints so far, can be merged, definitely works better than previous version.

**Pull request closed without merging**
